---

- name: Ensure Riemann download directory exists
  file: path={{ riemann_download_dir }} state=directory owner=root group=root mode=0755
  tags:
    - riemann-server

- name: Download Riemann release
  when: ansible_os_family == "Debian"
  get_url: url="https://aphyr.com/riemann/riemann_{{ riemann_version }}_all.deb" dest="{{ riemann_download_dir }}/riemann_{{ riemann_version }}.deb"
  tags:
    - riemann-server

- name: Download Riemann release
  when: ansible_os_family == "RedHat"
  get_url: url="https://aphyr.com/riemann/riemann-{{ riemann_version }}-1.noarch.rpm" dest="{{ riemann_download_dir }}/riemann-{{ riemann_version }}.rpm"
  tags:
    - riemann-server

- name: Install Riemann release
  when: ansible_os_family == "Debian"
  apt: deb="{{ riemann_download_dir }}/riemann_{{ riemann_version }}.deb" state=present
  tags:
    - riemann-server

- name: Install Riemann release
  when: ansible_os_family == "RedHat"
  yum: name="{{ riemann_download_dir}}/riemann-{{ riemann_version }}.rpm" state=present
  tags:
    - riemann-server

- name: Create configuration directory
  file: path={{ riemann_conf_dir }}/conf.d state=directory recurse=yes owner=root group=root mode=0755
  when: riemann_write_config
  tags:
    - riemann-server

- name: Create configuration file
  template: src=riemann.config.j2 dest={{ riemann_conf_dir }}/riemann.config owner=root group=root mode=0644
  when: riemann_write_config
  tags:
    - riemann-server
  notify: restart riemann

- name: Ensure Riemann Extra download directory exists
  file: path={{ riemann_extra_lib_dir }} state=directory owner=root group=root mode=0755
  tags:
    - riemann-server
  when: riemann_extra == true

- name: Download Riemann Extra release
  get_url: >
    url="https://github.com/rastandy/riemann-extra/releases/download/v-1.0/riemann-extra.jar"
    dest="{{ riemann_extra_lib_dir }}/riemann-extra.jar"
  tags:
    - riemann-server
  when: riemann_extra == true
  notify: restart riemann

- name: Create system config file
  template: src=riemann.sysconfig.j2 dest=/etc/sysconfig/riemann owner=root group=root mode=0644
  tags:
    - riemann-server
  notify: restart riemann

- name: Start Riemann server
  service: name=riemann state={{ riemann_state }} enabled={{ riemann_enable }}
  tags:
    - riemann-server
